version: '3'

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - ENV_VAR_NAME=value
    extra_hosts:
      - "host.docker.internal:host-gateway"
